### ISSUE TITLE
ReplAPI.it Integration?

### ISSUE THREAD

**Issue by rayhanadev** [doinkythederp/repldb#1]
Heya!

I really like your method of using ReplDB, (the synchronous refresh and async options). If you don't mind I would like to use some of these ideas when creating the ReplDB Database interface for my package, [ReplAPI.it](https://github.com/RayhanADev/ReplAPI.it). Just getting your permission before I try anything xD. Let me know what you think!

**Comment by lewisfm** [comment]
Of course! If I understand correctly, you'll be writing the code yourself instead of using this as a dependency, so [here's](https://docs.replit.com/misc/database) some info on the the database which might help with development.

Note that if you'd like to use the code in this repo directly (copy/paste), you'll need to follow the terms of the license.

**Comment by rayhanadev** [comment]
Thank you! Yeah you're correct I plan on using the *idea* of caching, sync/async db, etc. instead of copy-pasting the code itself. I'll look into the info as well, it should help :).

Thanks again!
